{% set name = "simplejson" %}
{% set version = "3.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  sha256: 5a4767ccc43b2dc771b9639ff168ffdab240bdf8d286ce304c7adc71269635dd

build:
  number: 0

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python

test:

  imports:
    - simplejson
    - simplejson.tests

  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simplejson/simplejson
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson
